# Generated by Django 2.0 on 2017-12-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=130)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=20)),
                ('image', models.BinaryField(blank=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
